# Ansible playbook here!
# - Ansible is based on playbooks like this one, where we use ansible commands to build an automation script
# - The hosts key refers to the systems where this playbook is going to be installed, here only one, but could be many systems with only one playbook
# - The become key is used to grant ansible administrator (sudo) privileges on the target machine.
# - A playbook can have several tasks, each of them precedeed by a dash. Here, we have a task that uses the "apt" ansible module to perform actions, for example here, is used to install firefox 
# - Each ansible module has a documentation page where how is it used is explained (also some useful code snippets are provided). For example the documentation of the package module is here https://docs.ansible.com/ansible/latest/modules/apt_module.html

---
  - name: Configuring RaspberryPis
    hosts: Raspberrys
    become: yes
    - name: Install my tools
      apt:
        pkg:
          - firefox-esr
        update_cache: yes
