# Ansible playbook here!
# - As ansible playbooks are YAML files, indentation must be correct. Each level is indented with two spaces
# - I have added some additional tasks to this play, one to uninstall some packages and another one to install Firefox
# - At the end, I have used the debug block to print a Hello world when ansible reachs that line 
---
  - name: Configuring RaspberryPis
    hosts: Raspberrys
    become: yes
    tasks:
    - name: Install my tools
      apt:
        pkg:
          - firefox-esr
        update_cache: yes
    - name: Create a user
      user:
        name: "arcones"
        groups: sudo
    - name: Hello world in ansible playbook
      debug:
        msg: "Hello world"
