version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build a docker container to test ansible playbooks
          command:  docker build -t raspbian-ansible-test .
      - run:
          name: Run first ansible playbook
          command: docker run raspbian-ansible-test:latest ansible-playbook playbook-1.yml
      - run:
          name: Run seconf ansible playbook
          command: docker run raspbian-ansible-test:latest ansible-playbook playbook-2.yml
      - run:
          name: Run complete ansible playbook
          command: docker run raspbian-ansible-test:latest ansible-playbook playbook-complete.yml
