version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build a docker container to test ansible playbooks
          command:  docker build -t raspbian-ansible-test .
      - run:
          name: Run first ansible playbook
          command: docker run raspbian-ansible-test:latest ansible-playbook playbook-1.yml
      - run:
          name: Run second ansible playbook
          command: docker run raspbian-ansible-test:latest ansible-playbook playbook-2.yml
      - run:
          name: Run third ansible playbook
          command: docker run raspbian-ansible-test:latest ansible-playbook playbook-3.yml
      - run:
          name: Run fourth ansible playbook
          command: docker run raspbian-ansible-test:latest ansible-playbook playbook-4.yml
